version: '3'
services:
  nginx:
    build: ./nginx
    volumes:
      - ./website/bedrock:/var/www/html
    ports:
      - '8080:80'
    depends_on:
      - php
  
  mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: mariadb
      MARIADB_DATABASE: mariadb
      MARIADB_USER: mariadb
    volumes:
      - ./data:/var/lib/mysql
  
  php:
    build: ./website
    env_file:
      - ./website/env/.env.production
    volumes:
      - ./website/bedrock:/var/www/html
  
  build_step:
    container_name: "Notes-build"
    build:
      context: .
      dockerfile: ./build/dockerfile
    volumes:
      - .:/app

networks:
  default:
    name: aqua
    external: true