version: '3'
services:
  nginx:
    build: ./nginx
    container_name: notes-wordpress-${ENV}
    volumes:
      - ./website/bedrock:/var/www/html
    depends_on:
      - php
    networks:
      - internal
      - external
  
  mariadb:
    image: mariadb
    restart: always
    container_name: notes-wordpress-db-${ENV}
    environment:
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USER}
    volumes:
      - ${DB_DATA_PATH}/${ENV}:/var/lib/mysql
    networks:
      - internal
  
  php:
    build: ./website
    container_name: notes-wordpress-php-${ENV}
    env_file:
      - ./website/env/.env.production
    environment:
      - DB_NAME=${DB_DATABASE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=notes-wordpress-db-${ENV}
    volumes:
      - ./website/bedrock:/var/www/html
    networks:
      - internal
  
  build_step:
    container_name: "notes-wordpress-build-${ENV}"
    build:
      context: .
      dockerfile: ./build/dockerfile
    volumes:
      - .:/app
    networks:
      - internal

networks:
  internal:
  external:
    name: aqua
    external: true