version: '3'
services:
  nginx:
    build: ./nginx
    volumes:
      - ./website/bedrock:/var/www/html
    depends_on:
      - php
  
  mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USER}
    volumes:
      - ./data:/var/lib/mysql
  
  php:
    build: ./website
    env_file:
      - ./website/env/.env.production
    environment:
      - DB_NAME=${DB_DATABASE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./website/bedrock:/var/www/html
  
  build_step:
    container_name: "Notes-build"
    build:
      context: .
      dockerfile: ./build/dockerfile
    volumes:
      - .:/app

networks:
  default:
    name: aqua
    external: true